SELECT YEAR,
       MONTH,
       SUM(TOTAL_BOOKINGS) OVER(ORDER BY YEAR, MONTH ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_BOOKINGS
FROM (
    SELECT t.YEAR, t.MONTH, COUNT(*) AS TOTAL_BOOKINGS
    FROM FACT_BOOKING f
    JOIN DIM_TIME t ON f.ID_ARRIVAL_DATE = t.ID_DATE
    GROUP BY t.YEAR, t.MONTH
) bookings_per_month
ORDER BY YEAR, MONTH;

SELECT h.HOTEL_TYPE,
       r.ROOM_TYPE,
       ROUND(CORR(f.ADR, f.LEAD_TIME),2) AS CORR_ADR_LEADTIME,
       ROUND(CORR(f.ADR, f.WEEKEND_NIGHTS + f.WEEK_NIGHTS),2) AS CORR_ADR_NIGHTS
FROM FACT_BOOKING f
JOIN DIM_HOTEL h ON f.ID_HOTEL = h.ID_HOTEL
JOIN DIM_ROOM r ON f.ID_ASSIGNED_ROOM = r.ID_ROOM
GROUP BY h.HOTEL_TYPE, r.ROOM_TYPE;

SELECT g.ID_GUEST,
       COUNT(f.ID_BOOKING) AS TOTAL_BOOKINGS,
       SUM(f.ADR * (f.WEEKEND_NIGHTS + f.WEEK_NIGHTS)) AS TOTAL_REVENUE,
       AVG(f.LEAD_TIME) AS AVG_LEAD_TIME
FROM FACT_BOOKING f
JOIN DIM_GUEST g ON f.ID_GUEST = g.ID_GUEST
GROUP BY g.ID_GUEST
ORDER BY TOTAL_REVENUE DESC
FETCH FIRST 10 ROWS ONLY;

SELECT h.HOTEL_TYPE,
       s.DISTRIBUTION_CHANNEL,
       d.DEPOSIT_TYPE,
       COUNT(f.ID_BOOKING) AS TOTAL_BOOKINGS,
       SUM(CASE WHEN bs.BOOKING_STATUS = 'Canceled' THEN 1 ELSE 0 END) AS TOTAL_CANCELLATIONS,
       ROUND(SUM(CASE WHEN bs.BOOKING_STATUS = 'Canceled' THEN 1 ELSE 0 END)/COUNT(*)*100, 2) AS CANCELLATION_RATE
FROM FACT_BOOKING f
JOIN DIM_HOTEL h ON f.ID_HOTEL = h.ID_HOTEL
JOIN DIM_SALES_CHANNEL s ON f.ID_SALES_CHANNEL = s.ID_CHANNEL
JOIN DIM_DEPOSIT d ON f.ID_DEPOSIT = d.ID_DEPOSIT
JOIN DIM_BOOKING_STATUTS bs ON f.ID_BOOKING_STATUS = bs.ID_STATUS
GROUP BY h.HOTEL_TYPE, s.DISTRIBUTION_CHANNEL, d.DEPOSIT_TYPE
ORDER BY CANCELLATION_RATE DESC;

SELECT t.YEAR,
       t.MONTH,
       COUNT(*) AS TOTAL_BOOKINGS,
       AVG(f.LEAD_TIME) AS AVG_LEAD_TIME,
       SUM(CASE WHEN f.LEAD_TIME > 30 THEN 1 ELSE 0 END) AS LONG_LEAD_BOOKINGS,
       ROUND(SUM(CASE WHEN f.LEAD_TIME > 30 THEN 1 ELSE 0 END)/COUNT(*)*100, 2) AS LONG_LEAD_PERCENT
FROM FACT_BOOKING f
JOIN DIM_TIME t ON f.ID_ARRIVAL_DATE = t.ID_DATE
GROUP BY t.YEAR, t.MONTH
ORDER BY t.YEAR, t.MONTH;

WITH revenue_per_hotel AS (
    SELECT h.HOTEL_TYPE,
           r.ROOM_TYPE,
           SUM(f.ADR) AS REVENUE
    FROM FACT_BOOKING f
    JOIN DIM_HOTEL h ON f.ID_HOTEL = h.ID_HOTEL
    JOIN DIM_ROOM r ON f.ID_ASSIGNED_ROOM = r.ID_ROOM
    GROUP BY h.HOTEL_TYPE, r.ROOM_TYPE
)
SELECT HOTEL_TYPE,
       ROOM_TYPE,
       REVENUE,
       ROUND(REVENUE / SUM(REVENUE) OVER(PARTITION BY HOTEL_TYPE) * 100, 2) AS MARKET_SHARE_PERCENT
FROM revenue_per_hotel
ORDER BY HOTEL_TYPE, MARKET_SHARE_PERCENT DESC;



